"""The provisioning state file (.provision/state.json).

It records the files the provisioning generated and their hashes. A generated
file may be overwritten or deleted only while its hash still matches, that is,
while the user has not edited it. A file without a record, or with a different
hash, belongs to the user.
"""

import json
import os

from . import fsutil

VERSION = 1


class State:
    def __init__(self, root):
        self.root = root
        self.path = os.path.join(root, fsutil.STATE_DIR, "state.json")
        self.data = {"version": VERSION, "files": {}}
        self.warnings = []

    def load(self):
        try:
            with open(self.path, encoding="utf-8") as f:
                data = json.load(f)
        except FileNotFoundError:
            return self
        except (OSError, ValueError) as e:
            self.warnings.append(f"{self.path} is unreadable and is ignored: {e}")
            return self
        if isinstance(data, dict) and data.get("version") == VERSION:
            data.setdefault("files", {})
            self.data = data
        else:
            self.warnings.append(f"{self.path} has an unknown format and is ignored")
        return self

    def save(self, owner):
        data = (json.dumps(self.data, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode("utf-8")
        try:
            with open(self.path, "rb") as f:
                if f.read() == data:
                    return
        except OSError:
            pass
        fsutil.write_atomic(self.path, data, owner)

    # ----- generated files -----

    def record(self, rel, digest):
        self.data["files"][rel] = digest

    def forget(self, rel):
        self.data["files"].pop(rel, None)

    def recorded(self, rel):
        return self.data["files"].get(rel)

    def is_ours(self, rel):
        """True if rel was generated by us and has not been edited since.

        A missing file with a record also counts as ours (nothing to protect).
        """
        digest = self.recorded(rel)
        if digest is None:
            return False
        path = os.path.join(self.root, rel)
        if not os.path.exists(path):
            return True
        return fsutil.sha256_file(path) == digest

    # ----- other sections -----

    def section(self, name):
        return self.data.setdefault(name, {})
